version: '3.9'

services:
  user-service:
    container_name: user-service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:6000
    deploy:
      restart_policy:
        condition: on-failure